name: Format, lint, and test

on:
  push

jobs:
  lint_and_check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install package and lint tools
        run: pip install ".[dev]"
      - name: Run tests
        run: pytest -vvv
      - name: Run lint
        run: bash scripts/lint.sh
